# Generated by Django 3.0.8 on 2020-07-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('availability', models.BooleanField()),
                ('price', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(choices=[('Action', 'Action and Adventute'), ("Children's", "Children's"), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Fairytale', 'Fairytale'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Poetry', 'Poetry'), ('Novel', 'Novel'), ('Self Help', 'Self Help'), ('Business', 'Business')], max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(default='author', on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
            ],
        ),
    ]
